### ISSUE TITLE
Europe

### ISSUE THREAD

**Issue by RaZok17** [DeathDefying/scripts#1]
[11:47:09.943] [mods] ERROR: Module "zerk-script" could not be loaded!
[11:47:09.948] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[11:47:09.950] Error: [dispatch] [zerk-script] hook: Error: version 13 of message (name: "S_LOGIN", code: 49367) is outdated and cannot be used anymore

Not working on Europe.

**Comment by FrostSigil** [comment]
> [11:47:09.950] Error: [dispatch] [zerk-script] hook: Error: version 13 of message (name: "S_LOGIN", code: 49367) is outdated and cannot be used anymore
> 
1.Open file: index.js in txt format
2.Find text: dispatch.hook('S_LOGIN', dispatch.majorPatchVersion >= 81 ? 13 : 12, (event)
3.Edit number: "13 : 12" to "14 : 13" 
Example: dispatch.hook('S_LOGIN', dispatch.majorPatchVersion >= 81 ? 14 : 13, (event) 
4.Save file. Completed! =))

**Comment by RaZok17** [comment]
Worked but sadly I'd assume that all opcodes like (C_START_TARGETED_SKILL and others) don't work for Europe...would probably need to rewrite everything to make it work.

**Comment by DeathDefying** [comment]
> [11:47:09.943] [mods] ERROR: Module "zerk-script" could not be loaded!
> [11:47:09.948] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
> [11:47:09.950] Error: [dispatch] [zerk-script] hook: Error: version 13 of message (name: "S_LOGIN", code: 49367) is outdated and cannot be used anymore
> 
> Not working on Europe.

everything should be fixed now
